In [5]:
for i in range(100,97,-1):
    print(str(i) + " bottles of beer on the wall")
    print(str(i) + " bottles of beer")
    print(" take one down, pass it around,")
    print(str(i-1) + " bottles of beer on the wall")

100 bottles of beer on the wall
100 bottles of beer
 take one down, pass it around,
99 bottles of beer on the wall
99 bottles of beer on the wall
99 bottles of beer
 take one down, pass it around,
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
 take one down, pass it around,
97 bottles of beer on the wall
100 bottles of beer on the wall
100 bottles of beer
 take one down, pass it around,
99 bottles of beer on the wall
99 bottles of beer on the wall
99 bottles of beer
 take one down, pass it around,
98 bottles of beer on the wall
98 bottles of beer on the wall
98 bottles of beer
 take one down, pass it around,
97 bottles of beer on the wall


In [6]:
def sing_verse(num):
    song = str(num) + " bottles of beer on the wall \n" + str(num) + " bottles of beer \n" + " take one down, pass it around, \n" + str(num-1) + " bottles of beer on the wall \n"
  
    return song

song = []

for i in range(100,97,-1):
    song.append(sing_verse(i))
print(song)

['100 bottles of beer on the wall \n100 bottles of beer \n take one down, pass it around, \n99 bottles of beer on the wall \n', '99 bottles of beer on the wall \n99 bottles of beer \n take one down, pass it around, \n98 bottles of beer on the wall \n', '98 bottles of beer on the wall \n98 bottles of beer \n take one down, pass it around, \n97 bottles of beer on the wall \n']
['100 bottles of beer on the wall \n100 bottles of beer \n take one down, pass it around, \n99 bottles of beer on the wall \n', '99 bottles of beer on the wall \n99 bottles of beer \n take one down, pass it around, \n98 bottles of beer on the wall \n', '98 bottles of beer on the wall \n98 bottles of beer \n take one down, pass it around, \n97 bottles of beer on the wall \n']


In [7]:
# vectorizing
import numpy as np

def sqrt_pos_unvec():
    a_vec = np.array([-2, -1, -3, -9, 7])
    is_pos = a_vec > 0
    a_vec[is_pos] = np.sqrt(a_vec[is_pos])

    return(a_vec)

result = sqrt_pos_unvec()
print(result)

[-2 -1 -3 -9  2]
[-2 -1 -3 -9  2]


In [9]:
# class example to get exact sqrt of 7
def sqrt_pos_unvec(x):
    if x > 0:
        return np.sqrt(x)
    else:
        return x
new_vec = []
a_vec = np.array([-2, -1, -3, -9, 7])
for val in a_vec:
    new_vec.append(sqrt_pos_unvec(val))
print(new_vec)

[-2, -1, -3, -9, 2.6457513110645907]
[-2, -1, -3, -9, 2.6457513110645907]


In [10]:
# class example
def sqrt_pos_vec(x):
    is_pos = x > 0 
    x[is_pos] = np.sqrt(x[is_pos])

    return x
print(a_vec)
print(sqrt_pos_vec(a_vec))


[-2 -1 -3 -9  7]
[-2 -1 -3 -9  2]
[-2 -1 -3 -9  7]
[-2 -1 -3 -9  2]


In [11]:
# mapping
song = map(sing_verse, range(100, 97, -1))
song = list(song)
print("".join(song))


100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 

100 bottles of beer on the wall 
100 bottles of beer 
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of beer on the wall 
99 bottles of beer 
 take one down, pass it around, 
98 bottles of beer on the wall 
98 bottles of beer on the wall 
98 bottles of beer 
 take one down, pass it around, 
97 bottles of beer on the wall 



In [17]:
def sing_verse_2(num, drink):
    song = str(num) + " bottles of " + drink + " on the wall \n"
    song = song + str(num) + " bottles of " + drink + "\n" 
    song = song + " take one down, pass it around, \n"
    song = song + str(num-1) + " bottles of " + drink + " on the wall \n"
  
    return song

In [18]:
nums = range(100, 97, -1)
drinks = ["beer", "milk", "lemonade"]
song = map(sing_verse_2, nums, drinks)
print("".join(list(song)))

100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of milk on the wall 
99 bottles of milk
 take one down, pass it around, 
98 bottles of milk on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 

100 bottles of beer on the wall 
100 bottles of beer
 take one down, pass it around, 
99 bottles of beer on the wall 
99 bottles of milk on the wall 
99 bottles of milk
 take one down, pass it around, 
98 bottles of milk on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 



In [20]:
# lambda functions: changes beer to lemonade
def sing_verse_lemonade(num):
      return sing_verse_2(num, "lemonade")

song = map(sing_verse_lemonade, nums)
print("".join(list(song)))

100 bottles of lemonade on the wall 
100 bottles of lemonade
 take one down, pass it around, 
99 bottles of lemonade on the wall 
99 bottles of lemonade on the wall 
99 bottles of lemonade
 take one down, pass it around, 
98 bottles of lemonade on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 

100 bottles of lemonade on the wall 
100 bottles of lemonade
 take one down, pass it around, 
99 bottles of lemonade on the wall 
99 bottles of lemonade on the wall 
99 bottles of lemonade
 take one down, pass it around, 
98 bottles of lemonade on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 



In [21]:
# lambda replaces beer with lemonade more easily
song = map(lambda i: sing_verse_2(i, "lemonade"), nums)
print("".join(list(song)))

100 bottles of lemonade on the wall 
100 bottles of lemonade
 take one down, pass it around, 
99 bottles of lemonade on the wall 
99 bottles of lemonade on the wall 
99 bottles of lemonade
 take one down, pass it around, 
98 bottles of lemonade on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 

100 bottles of lemonade on the wall 
100 bottles of lemonade
 take one down, pass it around, 
99 bottles of lemonade on the wall 
99 bottles of lemonade on the wall 
99 bottles of lemonade
 take one down, pass it around, 
98 bottles of lemonade on the wall 
98 bottles of lemonade on the wall 
98 bottles of lemonade
 take one down, pass it around, 
97 bottles of lemonade on the wall 



In [23]:
import pandas as pd
dat = pd.DataFrame({"x": [99, 50, 2], "y": [1, 2, 3]})

dat.apply(np.sqrt)

x         y
0  9.949874  1.000000
1  7.071068  1.414214
2  1.414214  1.732051

In [24]:
dat.apply(np.sum, axis=1)

0    100
1     52
2      5
dtype: int64